version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements_ci.txt" }}
      - run:
          command: |
            python3 -m pip install tox
      - run:
          name: Running tests
          command: |
            tox
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements_ci.txt" }}
          paths:
            - ".tox"
